### ISSUE TITLE
Bug: boot rev. 5.0.0

### ISSUE THREAD

**Issue by beckadamtheinventor** [TheMachine02/Cauldron#1]
Bug: Installing a custom OS on boot rev. 5.0.0 with Cauldron installed causes the calc to hang, and repeatedly NMI. whereas without the patch it works just fine.

**Comment by TheMachine02** [comment]
I don't really see why ... Cauldron + my custom OS work actually, and Cauldron is fully compatible with what the TI OS does. Do you have any binary so I can debug ?

**Comment by beckadamtheinventor** [comment]
https://github.com/beckadamtheinventor/BOS
And it only breaks on rev 5.0.0 as far as I know.

**Comment by TheMachine02** [comment]
As I pointed out, the build.sh provided can't build with latest fasmg. I kinda don't have the time to check through all the dependencie nightmare, so it would be nice of you to include an executable

**Comment by beckadamtheinventor** [comment]
oops, sorry.
[BOSOS.zip](https://github.com/TheMachine02/Cauldron/files/5319044/BOSOS.zip)

**Comment by TheMachine02** [comment]
Thanks.

Quick head note : the bug is not reproductible on CEmu, so something strange does occur...
